---
env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    "no-restricted-syntax": "off",
    "no-await-in-loop": "off",
    "no-continue": "off",
    "no-underscore-dangle": "off",
    "no-param-reassign": "error",
    "max-len":
      [
        "error",
        { code: 125, ignoreComments: true, ignoreTrailingComments: true },
      ],
    "consistent-return": "error",
    "no-template-curly-in-string": "warn",
    "no-plusplus": ["warn", { allowForLoopAfterthoughts: true }],
    "no-unused-vars":
      ["error", { ignoreRestSiblings: true, argsIgnorePattern: "^_" }],
    "no-console": "warn",
    camelcase: "error",
    "no-return-await": "off",
    "class-methods-use-this": "error",
    "import/no-extraneous-dependencies":
      ["off", { optionalDependencies: false }],
    "prefer-destructuring": "warn",
    "object-curly-newline": "off",
    "no-control-regex": "off",
    "prefer-const": ["error", { destructuring: "all" }],
    "lines-between-class-members":
      ["error", "always", { exceptAfterSingleLine: true }],
    "semi-style": ["error", "last"],
    "strict": ["error", "global"],
    "indent": ["error", 2],
  }
