---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  workflow_dispatch:
  push:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          # Change to 'master' if your main branch differs
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # ENABLED
          VALIDATE_JSCPD_ALL_CODEBASE: true
          # VALIDATE_HTML: true
          # VALIDATE_CSS: true
          # VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_TYPESCRIPT_ES: true
          # VALIDATE_TSX: true
          # VALIDATE_JSON: true
          # VALIDATE_SQL: true

          # DISABLED
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_ENV: false
          VALIDATE_YAML: false
          VALIDATE_JAVA: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_MARKDOWN: false
          VALIDATE_GITLEAKS: false
          VALIDATE_ANSIBLE: false
          VALIDATE_ARM: false
          VALIDATE_BASH: false
          VALIDATE_CLOJURE: false
          VALIDATE_COFFEESCRIPT: false
          VALIDATE_CPP: false
          VALIDATE_CRYSTAL: false
          VALIDATE_DART: false
          VALIDATE_DOCKER: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_GO: false
          VALIDATE_GROOVY: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JULIA: false
          VALIDATE_KOTLIN: false
          VALIDATE_LATEX: false
          VALIDATE_LUA: false
          VALIDATE_OPENAPI: false
          VALIDATE_PERL: false
          VALIDATE_PHP: false
          VALIDATE_POWERSHELL: false
          VALIDATE_PROTOBUF: false
          VALIDATE_PYTHON: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_R: false
          VALIDATE_RAKU: false
          VALIDATE_RUBY: false
          VALIDATE_RUST: false
          VALIDATE_SCALA: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_SHELLCHECK: false
          VALIDATE_TERRAFORM: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_V: false
          VALIDATE_XML: false
          
